import { translateTextBy } from "@/utils/i18n";

export const HotGame = [
  {
    logo: "/_always_win_/lobby/logo/classify/content/CN-101.png",
    lottoID: "2004",
    name: "奇趣分分彩",
    country: "CN",
    lottoClassify: "101",
    webSite: "https://77tj.org",
    status: "1",
    statusPlatform: "1",
    source: "third",
  },
  {
    logo: "/_always_win_/lobby/logo/classify/content/CN-101.png",
    lottoID: "2003",
    name: "QQ分分彩",
    country: "CN",
    lottoClassify: "101",
    webSite: "https://77tj.org",
    status: "1",
    statusPlatform: "1",
    source: "third",
  },
  {
    logo: "/_always_win_/lobby/logo/classify/content/CN-101.png",
    lottoID: "3001",
    name: "波场分分彩",
    country: "CN",
    lottoClassify: "101",
    webSite: "https://tronscan.org/#/",
    status: "1",
    statusPlatform: "1",
    source: "third",
  },
  {
    logo: "/_always_win_/lobby/logo/classify/content/CN-101.png",
    lottoID: "1001",
    name: "澳洲幸运5",
    country: "CN",
    lottoClassify: "101",
    webSite: "https://1689615.com/view/aozxy5/ssc_index.html",
    status: "1",
    statusPlatform: "1",
    source: "third",
  },
  {
    logo: "/_always_win_/lobby/logo/classify/content/CN-107.png",
    lottoID: "1005",
    name: "福彩3D",
    categoryName: "3D",
    country: "CN",
    lottoClassify: "107",
    webSite: "https://1689615.com/view/wanfaguize/FCSD.html",
    status: "1",
    statusPlatform: "1",
    source: "third",
  },
];

export const Menus = [
  {
    title: translateTextBy("web.i18nFront.title.hotGame"),
    i18nTitle: "hot",
    name: "hot",
    path: "/hot",
    icon: "icon_game_hot",
  },
  {
    title: translateTextBy("web.i18nFront.title.lottery"),
    i18nTitle: "lottery",
    name: "lottery",
    path: "/lottery",
    icon: "icon_game_lottery",
    showMore: true,
  },
  {
    title: translateTextBy("web.i18nFront.title.realbet"),
    i18nTitle: "realbet",
    name: "realbet",
    path: "/realbet",
    icon: "icon_game_real",
  },
  {
    title: translateTextBy("web.i18nFront.title.chess"),
    i18nTitle: "chess",
    name: "chess",
    path: "/chess",
    icon: "icon_game_chess",
  },
  {
    title: translateTextBy("web.i18nFront.title.sports"),
    i18nTitle: "sports",
    name: "sports",
    path: "/sports",
    icon: "icon_game_sports",
    size: "30",
  },
  {
    title: translateTextBy("web.i18nFront.title.fish"),
    i18nTitle: "fish",
    name: "fish",
    path: "/fish",
    icon: "icon_game_fish",
  },
  {
    title: translateTextBy("web.i18nFront.title.egame"),
    i18nTitle: "egame",
    name: "egame",
    path: "/egame",
    icon: "icon_game_egame",
  },
  {
    title: translateTextBy("web.i18nFront.title.history"),
    i18nTitle: "history",
    name: "history",
    path: "/history",
    icon: "icon_game_history",
    size: "30",
  },
];
